### ISSUE TITLE
Missing weapon skills

### ISSUE THREAD

**Issue by Zoidwaffle** [heyitsbench/mod-arac#19] opened 2023-01-15 10:44 UTC
Hi, if you start as a dwarf druid you only get the staves as a weapons skill. You do not get the dagger/mace as a night elf does. I didn't check other race/class combos.

The reference here https://www.azerothcore.org/wiki/playercreateinfo_spell_custom says you should enable "PlayerStart.AllSpells" which doesn't exist, but instead in worldserver.conf I enabled this:

PlayerStart.CustomSpells = 1

As it sound like that should be needed, since the included SQL has a lot of changes for table playercreateinfo_spell_custom.

But no luck, it's not working for me. If the above "PlayerStart.CustomSpells = 1" had fixed it, I would just have made a PR with an update to the README.md file.

I'm currently on mod-arac 2e7040352385f4cff9a9fce77cf562d65b689a19 and azerothcore 0df153b8ddaa8b28002462ce955c509b9fe04aed (less than 48 hours old).

**Comment by Zoidwaffle** [comment] 2023-01-15 13:28
A bit more info.

When creating a dwarf druid, I get this in the worldserver:

`AC> Player::addSpell: Non-existed in SpellStore spell #26993 request.
Player::addSpell: Non-existed in SpellStore spell #26999 request.
STORAGE: Can't equip or store initial item 6948 for race 3 class 11, error msg = 17
Player::addSpell: Non-existed in SpellStore spell #26993 request.`

And here a gnome paladin:

`AC> Player::addSpell: Non-existed in SpellStore spell #1020 request.
Player::addSpell: Non-existed in SpellStore spell #5627 request.
Player::addSpell: Non-existed in SpellStore spell #25895 request.
Player::addSpell: Non-existed in SpellStore spell #27144 request.
Player::addSpell: Non-existed in SpellStore spell #27145 request.
Player::addSpell: Non-existed in SpellStore spell #27148 request.
Player::addSpell: Non-existed in SpellStore spell #27155 request.
Player::addSpell: Non-existed in SpellStore spell #27158 request.
Player::addSpell: Non-existed in SpellStore spell #27160 request.
Player::addSpell: Non-existed in SpellStore spell #27166 request.
Player::addSpell: Non-existed in SpellStore spell #27169 request.
Player::addSpell: Non-existed in SpellStore spell #31895 request.
STORAGE: Can't equip or store initial item 6948 for race 7 class 2, error msg = 17`

I'm currently not sure what this indicates.

The error might be local, aka just an issue here, but that should be very easy to verify at least.

**Comment by heyitsbench** [comment] 2023-01-15 16:49
There are a couple of issues open related to weapon skill issues, the root issue is a lack of changes to SkillRaceClassInfo.DBC. Anything added to playercreateinfo_spell_custom, if it works, is pretty much just a hack. Same goes for playercreateinfo_skills.

**Comment by Zoidwaffle** [comment] 2023-01-15 17:14
Thanks for the info.

So a proper fix would be modifying the `SkillRaceClassInfo.dbc` and perhaps `SkillLineAbility.dbc`?

Not that I know how to do that, unfortunately (not yet at least).

But if that was done, all the inserts in playercreateinfo_spell_custom could then be discarded I guess.

**Comment by heyitsbench** [comment] 2023-01-21 15:37
> I still had to learn the 'gun spell', but that could easily be fixed within the module (or Eluna) I think.

Reason for this is one of two things: either the flags for the entry aren't set up correctly, or it needs to be added in the client-side patch. Based on the lack of info on flags on the [Wowdev wiki](https://wowdev.wiki/DB/SkillRaceClassInfo), I'm going to assume it's the latter.

**Comment by mibeal** [comment] 2023-01-30 03:43
> I tried something and it works
> 
> Make these changes in skillraceclassinfo_dbc
> 
> ![image](https://user-images.githubusercontent.com/114336867/213871775-78ebe161-4ce7-4437-8553-fd068907c3c5.png)
> 
> Don't worry, SkillRaceClassInfo.dbc's last ID is 970.
> 
> ```sql
> DELETE FROM `skillraceclassinfo_dbc` WHERE `ID`=1000;
> INSERT INTO `skillraceclassinfo_dbc` (`ID`, `SkillID`, `RaceMask`, `ClassMask`, `Flags`, `MinLevel`, `SkillTierID`, `SkillCostIndex`) VALUES (1000, 46, 32767, 4, 128, 1, 0, 0);
> ```
> 
> * restart world-server
> * create a human hunter
> * .learn 266 ([Guns, rank 1 enUS] [passive])
> * equip ranged weapon and logout, gun will be equipped in character screen
> * log back in
> * gun still equipped
> 
> My process:
> 
> I loaded SkillRaceClassInfo.dbc into DBC Viewer and looked for a column with 46 (gun skill ID) in it. With the help of Keira I calculated the RaceMask and ClassMask since I'm bad at math :( The value in Flags I just copied over, I can't find any info on that. SkillTierID and SkillCostIndex seems to be related to professions so I left them at 0.
> 
> I still had to learn the 'gun spell', but that could easily be fixed within the module (or Eluna) I think.
> 
> Unfortunately I don't have much time this weekend, but I'll try to make an sql file in the near future. It'll take some time because of the inefficient process.

I was able to take your process and add one handed swords to Blood Elf Warrior, following your example and looking up the appropriate ID's.  

![image](https://user-images.githubusercontent.com/24191594/215383080-515f5f40-1884-47ad-95e6-3a76f28abc5a.png)

**Comment by Zoidwaffle** [comment] 2023-02-02 19:00
I just wanted to add that I think it's awesome you are all looking into this.

I hope to get some time to test things as well, perhaps even contribute towards a solution. Having this feature work would rock for a fun/awesome non-Blizz-like experience. (Which is the best kind of experience).

**Comment by heyitsbench** [comment] 2023-02-02 19:44
To be clear, if anyone has a solution using a query to add to the `skillraceclassinfo_dbc` table and is willing to submit a PR, I personally would approve it, (Assuming it works, of course 😛) but I will not be fixing it myself that way. It is worth pointing out that this issue is pretty much a duplicate of #8 and #16, so any PR would preferably include skill fixes for those as well.

**Comment by deadcorpseeater** [comment] 2023-03-22 13:08
> I tried something and it works
> 
> Make these changes in skillraceclassinfo_dbc
> 
> ![image](https://user-images.githubusercontent.com/114336867/213871775-78ebe161-4ce7-4437-8553-fd068907c3c5.png)
> 
> Don't worry, SkillRaceClassInfo.dbc's last ID is 970.
> 
> ```sql
> DELETE FROM `skillraceclassinfo_dbc` WHERE `ID`=1000;
> INSERT INTO `skillraceclassinfo_dbc` (`ID`, `SkillID`, `RaceMask`, `ClassMask`, `Flags`, `MinLevel`, `SkillTierID`, `SkillCostIndex`) VALUES (1000, 46, 32767, 4, 128, 1, 0, 0);
> ```
> 
> * restart world-server
> * create a human hunter
> * .learn 266 ([Guns, rank 1 enUS] [passive])
> * equip ranged weapon and logout, gun will be equipped in character screen
> * log back in
> * gun still equipped
> 
> My process:
> 
> I loaded SkillRaceClassInfo.dbc into DBC Viewer and looked for a column with 46 (gun skill ID) in it. With the help of Keira I calculated the RaceMask and ClassMask since I'm bad at math :( The value in Flags I just copied over, I can't find any info on that. SkillTierID and SkillCostIndex seems to be related to professions so I left them at 0.
> 
> I still had to learn the 'gun spell', but that could easily be fixed within the module (or Eluna) I think.
> 
> Unfortunately I don't have much time this weekend, but I'll try to make an sql file in the near future. It'll take some time because of the inefficient process.

what do you use to read dbc files?

**Comment by Parkan1986** [comment] 2023-04-04 06:52
There is also a bug like on trinitycore version of ARAC that for example night elfs paladins cant use one handed swords.they just not get such skill.

**Closed** 2023-04-28 14:44 UTC
